name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install NBGV
      run: dotnet tool install -g nbgv
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Find nuget package
      id: find-nupkg
      run: |
        npkgFilePath=$(find ${{ github.workspace }}/osocli/bin/Release/ -type f -name '*.nupkg') \
        echo "nuget package path: $npkgFilePath"
        echo "::set-output name=nugetPkgPath::$npkgFilePath" \
    - name: Publish package
      if: ${{ steps.find-nupkg.nugetPkgPath != '' }}
      run: dotnet nuget push ${{ steps.find-nupkg.nugetPkgPath }} --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
      
