name: .NET

on:
  push:
    branches: [ master ]
    paths:
      - 'osocli/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install NBGV
      run: dotnet tool install -g nbgv
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: cd osocli && dotnet build --no-restore -c Release
    - name: Find nuget package
      id: find-nupkg
      run: echo "::set-output name=nugetPkgPath::$(find ${{ github.workspace }}/osocli/osocli/bin/Release/ -type f -name '*.nupkg')" \
    - name: Publish package
      if: ${{ steps.find-nupkg.outputs.nugetPkgPath != '' }}
      run: dotnet nuget push ${{ steps.find-nupkg.outputs.nugetPkgPath }} --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
      
