name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install NBGV
      run: dotnet tool install -g nbgv
    - name: Build
      run: dotnet build --no-restore
    - name: Set Nuget package version
      run: |
        npkgVersion=$(nbgv get-version -v NugetPackageVersion) \
        npkgFilePath=$(find ${GITHUB_WORKSPACE}/osocli/bin/Release -type f -name "*.nupkg" \
        newNpkgName="oso.cli.${npkgVersion}.nupkg" \
        newNpkgPath="${GITHUB_WORKSPACE}/osocli/bin/Release/${newNpkgName}" \
        cp $npkgFilePath $newNpkgPath \
        dotnet nuget push $newNpkgPath --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
      
